name: "SharedInventory"
version: 0.0.1-SNAPSHOT
softdepend: # todo: edit here every time
  - TomeitoLib
main: xyz.acrylicstyle.test.SharedInventory
commands:
  add:
    description: ""
  removeall:
    description: ""
  start:
    description: ""